name: 'Git Tag Action'
description: 'Add a git tag to the current workflow commit'
author: 'author-name'
inputs:
  MESSAGE:
     type: string
     descrption: MESSAGE

runs:
  using: "composite"
  steps:
    - name: Run a one-line script
      run: echo Hello, world! and input message is ${{ inputs.MESSAGE }} 
      shell: bash

