name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: "production"
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
