name: Input Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "dev"
      version:
        description: "App version"
        required: false

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Version: ${{ inputs.version }}"
          
