name: S B
on:
  workflow_dispatch:
    inputs:
      repos:
        required: true
        default: "test,terraform"
        type: string # like repo1,repo2,repo3
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      repo_list: ${{ steps.vars.outputs.repo_list }}
    steps:
      - name: Create an array of repositories
        id: vars
        run: echo "::set-output name=repo_list::$(jq 'split(",")' -Rc <(echo '${{ inputs.repos }}'))"
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.setup.outputs.repo_list) }}
    steps:
    - name: build project ${{ matrix.repo }}
      run: echo "project=${{ matrix.repo }}"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: stale ${{ matrix.repo }}
      #        uses: basivireddy/github-actions-common/stale@main
      uses: ./.github/workflows/actions/stale
      with:
        repo_name: "${{ matrix.repo }}"